version: '3.7'
services:

  pixvulture1:
    container_name: pixvulture1
    hostname: pixvulture1
    image: jpcairesf/pixvulture:latest
    pull_policy: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "1"
#          memory: "200MB"

  pixvulture2:
    container_name: pixvulture2
    hostname: pixvulture2
    image: jpcairesf/pixvulture:latest
    pull_policy: always
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "1"
#          memory: "200MB"

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
#          memory: "140MB"

  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pixvulture1
      - pixvulture2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "1"
#          memory: "10MB"

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
#      PGADMIN_DEFAULT_PASSWORD: "admin"
#    ports:
#      - "16543:80"
#    depends_on:
#      - postgres