version: '3.7'
services:

  pixvulture1:
    container_name: pixvulture1
    image: jpcairesf/pixvulture:latest
    pull_policy: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  pixvulture2:
    container_name: pixvulture2
    image: jpcairesf/pixvulture:latest
    pull_policy: always
    ports:
      - "8082:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "5432:5432"

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres